nodeLinker: node-modules

packageExtensions:
  # awaiting fix: https://github.com/EndemolShineGroup/cosmiconfig-typescript-loader/issues/147
  '@endemolshinegroup/cosmiconfig-typescript-loader@*':
    peerDependenciesMeta:
      typescript:
        optional: true